ARG BASE_IMAGE

FROM ${BASE_IMAGE}

WORKDIR /app

# build args
ARG APP_ENV
ARG APP_PORT

# runtime env
ENV APP_ENV=$APP_ENV
ENV PORT=$APP_PORT

COPY . .

RUN pip install -r requirements.txt

CMD ["python", "app.py"]