name: PR Merge

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "PR was merged"
          else
            echo "PR was closed but NOT merged"
          fi